// Code generated by envgen. DO NOT EDIT.
package main

import (
	"fmt"
	"os"
	"strconv"
	"sync"

	"github.com/mxkacsa/tinyconf"
)

// GameConfig holds configuration values for gameConfig
type GameConfig struct {
	Speed           float64 `json:"speed"`
	MaxPlayers      int32   `json:"maxPlayers"`
	EnableDebug     bool    `json:"enableDebug"`
	GameMode        string  `json:"gameMode"`
	RoundDuration   int32   `json:"roundDuration"`
	StartingScore   int64   `json:"startingScore"`
	AllowSpectators bool    `json:"allowSpectators"`
	TickRate        int32   `json:"tickRate" env:"GAME_TICK_RATE"`
}

// DefaultGameConfig returns a new GameConfig with default values
func DefaultGameConfig() *GameConfig {
	return &GameConfig{
		Speed:           1,
		MaxPlayers:      4,
		EnableDebug:     false,
		GameMode:        "classic",
		RoundDuration:   60,
		StartingScore:   0,
		AllowSpectators: true,
		TickRate:        20,
	}
}

// Validate validates the configuration values
func (c *GameConfig) Validate() error {
	if c.Speed < 0.1 {
		return fmt.Errorf("Speed must be >= 0.1, got %v", c.Speed)
	}
	if c.Speed > 10 {
		return fmt.Errorf("Speed must be <= 10, got %v", c.Speed)
	}
	if c.MaxPlayers < 2 {
		return fmt.Errorf("MaxPlayers must be >= 2, got %v", c.MaxPlayers)
	}
	if c.MaxPlayers > 16 {
		return fmt.Errorf("MaxPlayers must be <= 16, got %v", c.MaxPlayers)
	}
	if c.GameMode != "classic" && c.GameMode != "ranked" && c.GameMode != "casual" {
		return fmt.Errorf("GameMode must be one of [classic, ranked, casual], got %v", c.GameMode)
	}
	if c.RoundDuration < 10 {
		return fmt.Errorf("RoundDuration must be >= 10, got %v", c.RoundDuration)
	}
	if c.RoundDuration > 600 {
		return fmt.Errorf("RoundDuration must be <= 600, got %v", c.RoundDuration)
	}
	if c.TickRate < 1 {
		return fmt.Errorf("TickRate must be >= 1, got %v", c.TickRate)
	}
	if c.TickRate > 60 {
		return fmt.Errorf("TickRate must be <= 60, got %v", c.TickRate)
	}
	return nil
}

// LoadFromEnv loads values from environment variables (overrides existing values)
func (c *GameConfig) LoadFromEnv() {
	if v := os.Getenv("GAME_CONFIG_SPEED"); v != "" {
		if parsed, err := strconv.ParseFloat(v, 64); err == nil {
			c.Speed = float64(parsed)
		}
	}
	if v := os.Getenv("GAME_CONFIG_MAX_PLAYERS"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.MaxPlayers = int32(parsed)
		}
	}
	if v := os.Getenv("GAME_CONFIG_ENABLE_DEBUG"); v != "" {
		c.EnableDebug = v == "true" || v == "1"
	}
	if v := os.Getenv("GAME_CONFIG_GAME_MODE"); v != "" {
		c.GameMode = v
	}
	if v := os.Getenv("GAME_CONFIG_ROUND_DURATION"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.RoundDuration = int32(parsed)
		}
	}
	if v := os.Getenv("GAME_CONFIG_STARTING_SCORE"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.StartingScore = int64(parsed)
		}
	}
	if v := os.Getenv("GAME_CONFIG_ALLOW_SPECTATORS"); v != "" {
		c.AllowSpectators = v == "true" || v == "1"
	}
	if v := os.Getenv("GAME_TICK_RATE"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.TickRate = int32(parsed)
		}
	}
}

var (
	gameConfigInstance *GameConfig
	gameConfigOnce     sync.Once
	gameConfigConf     *tinyconf.TinyConf
)

// GetGameConfig returns the singleton instance of GameConfig
// It loads from config file on first call, or creates with defaults if not exists
func GetGameConfig() *GameConfig {
	gameConfigOnce.Do(func() {
		gameConfigInstance = DefaultGameConfig()
		gameConfigConf = tinyconf.NewTinyConf("gameConfig.json")

		// Load from file (creates with defaults if not exists)
		_ = gameConfigConf.Load(gameConfigInstance)

		// Override with environment variables
		gameConfigInstance.LoadFromEnv()
	})
	return gameConfigInstance
}

// ReloadGameConfig reloads the configuration from file
func ReloadGameConfig() error {
	if gameConfigConf == nil {
		GetGameConfig() // Initialize if not done
	}

	if err := gameConfigConf.Load(gameConfigInstance); err != nil {
		return err
	}

	// Override with environment variables
	gameConfigInstance.LoadFromEnv()

	return gameConfigInstance.Validate()
}

// SaveGameConfig saves the current configuration to file
func SaveGameConfig() error {
	if gameConfigConf == nil {
		GetGameConfig() // Initialize if not done
	}

	if err := gameConfigInstance.Validate(); err != nil {
		return err
	}

	return gameConfigConf.Save(gameConfigInstance)
}

// SetGameConfigPath sets the config file path (must be called before first GetGameConfig)
func SetGameConfigPath(path string) {
	gameConfigConf = tinyconf.NewTinyConf(path)
}

// MatchmakingConfig holds configuration values for matchmakingConfig
type MatchmakingConfig struct {
	EnableSBMM   bool  `json:"enableSBMM"`
	MaxSkillGap  int32 `json:"maxSkillGap"`
	QueueTimeout int32 `json:"queueTimeout"`
	MinPlayers   int32 `json:"minPlayers"`
}

// DefaultMatchmakingConfig returns a new MatchmakingConfig with default values
func DefaultMatchmakingConfig() *MatchmakingConfig {
	return &MatchmakingConfig{
		EnableSBMM:   true,
		MaxSkillGap:  500,
		QueueTimeout: 120,
		MinPlayers:   2,
	}
}

// Validate validates the configuration values
func (c *MatchmakingConfig) Validate() error {
	if c.MaxSkillGap < 100 {
		return fmt.Errorf("MaxSkillGap must be >= 100, got %v", c.MaxSkillGap)
	}
	if c.MaxSkillGap > 2000 {
		return fmt.Errorf("MaxSkillGap must be <= 2000, got %v", c.MaxSkillGap)
	}
	if c.QueueTimeout < 30 {
		return fmt.Errorf("QueueTimeout must be >= 30, got %v", c.QueueTimeout)
	}
	if c.QueueTimeout > 600 {
		return fmt.Errorf("QueueTimeout must be <= 600, got %v", c.QueueTimeout)
	}
	if c.MinPlayers < 2 {
		return fmt.Errorf("MinPlayers must be >= 2, got %v", c.MinPlayers)
	}
	if c.MinPlayers > 10 {
		return fmt.Errorf("MinPlayers must be <= 10, got %v", c.MinPlayers)
	}
	return nil
}

// LoadFromEnv loads values from environment variables (overrides existing values)
func (c *MatchmakingConfig) LoadFromEnv() {
	if v := os.Getenv("MATCHMAKING_CONFIG_ENABLE_S_B_M_M"); v != "" {
		c.EnableSBMM = v == "true" || v == "1"
	}
	if v := os.Getenv("MATCHMAKING_CONFIG_MAX_SKILL_GAP"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.MaxSkillGap = int32(parsed)
		}
	}
	if v := os.Getenv("MATCHMAKING_CONFIG_QUEUE_TIMEOUT"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.QueueTimeout = int32(parsed)
		}
	}
	if v := os.Getenv("MATCHMAKING_CONFIG_MIN_PLAYERS"); v != "" {
		if parsed, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.MinPlayers = int32(parsed)
		}
	}
}

var (
	matchmakingConfigInstance *MatchmakingConfig
	matchmakingConfigOnce     sync.Once
	matchmakingConfigConf     *tinyconf.TinyConf
)

// GetMatchmakingConfig returns the singleton instance of MatchmakingConfig
// It loads from config file on first call, or creates with defaults if not exists
func GetMatchmakingConfig() *MatchmakingConfig {
	matchmakingConfigOnce.Do(func() {
		matchmakingConfigInstance = DefaultMatchmakingConfig()
		matchmakingConfigConf = tinyconf.NewTinyConf("matchmakingConfig.json")

		// Load from file (creates with defaults if not exists)
		_ = matchmakingConfigConf.Load(matchmakingConfigInstance)

		// Override with environment variables
		matchmakingConfigInstance.LoadFromEnv()
	})
	return matchmakingConfigInstance
}

// ReloadMatchmakingConfig reloads the configuration from file
func ReloadMatchmakingConfig() error {
	if matchmakingConfigConf == nil {
		GetMatchmakingConfig() // Initialize if not done
	}

	if err := matchmakingConfigConf.Load(matchmakingConfigInstance); err != nil {
		return err
	}

	// Override with environment variables
	matchmakingConfigInstance.LoadFromEnv()

	return matchmakingConfigInstance.Validate()
}

// SaveMatchmakingConfig saves the current configuration to file
func SaveMatchmakingConfig() error {
	if matchmakingConfigConf == nil {
		GetMatchmakingConfig() // Initialize if not done
	}

	if err := matchmakingConfigInstance.Validate(); err != nil {
		return err
	}

	return matchmakingConfigConf.Save(matchmakingConfigInstance)
}

// SetMatchmakingConfigPath sets the config file path (must be called before first GetMatchmakingConfig)
func SetMatchmakingConfigPath(path string) {
	matchmakingConfigConf = tinyconf.NewTinyConf(path)
}
