// Code generated by envgen. DO NOT EDIT.


/**
 * GameConfig configuration interface
 */
export interface GameConfig {
  /** Speed configuration value */
  speed: number;
  /** MaxPlayers configuration value */
  maxPlayers: number;
  /** EnableDebug configuration value */
  enableDebug: boolean;
  /** GameMode configuration value */
  gameMode: string;
  /** RoundDuration configuration value */
  roundDuration: number;
  /** StartingScore configuration value */
  startingScore: number;
  /** AllowSpectators configuration value */
  allowSpectators: boolean;
  /** TickRate configuration value */
  tickRate: number;
}

/**
 * Default GameConfig configuration values
 */
export const defaultGameConfig: GameConfig = {
  speed: 1,
  maxPlayers: 4,
  enableDebug: false,
  gameMode: 'classic',
  roundDuration: 60,
  startingScore: 0,
  allowSpectators: true,
  tickRate: 20,
};

/**
 * Validate GameConfig configuration
 * @returns Array of error messages (empty if valid)
 */
export function validateGameConfig(config: GameConfig): string[] {
  const errors: string[] = [];
  if (config.speed < 0.1) { errors.push('Speed must be >= 0.1'); }
  if (config.speed > 10) { errors.push('Speed must be <= 10'); }
  if (config.maxPlayers < 2) { errors.push('MaxPlayers must be >= 2'); }
  if (config.maxPlayers > 16) { errors.push('MaxPlayers must be <= 16'); }
  if (!['classic', 'ranked', 'casual'].includes(config.gameMode)) { errors.push('GameMode must be one of [classic, ranked, casual]'); }
  if (config.roundDuration < 10) { errors.push('RoundDuration must be >= 10'); }
  if (config.roundDuration > 600) { errors.push('RoundDuration must be <= 600'); }
  if (config.tickRate < 1) { errors.push('TickRate must be >= 1'); }
  if (config.tickRate > 60) { errors.push('TickRate must be <= 60'); }
  return errors;
}

/**
 * GameConfig configuration metadata for UI generation
 */
export const gameConfigSchema = {
  speed: {
    type: 'float64' as const,
    default: 1,
    min: 0.1,
    max: 10,
  },
  maxPlayers: {
    type: 'int32' as const,
    default: 4,
    min: 2,
    max: 16,
  },
  enableDebug: {
    type: 'bool' as const,
  },
  gameMode: {
    type: 'string' as const,
    default: 'classic',
    options: ['classic', 'ranked', 'casual'] as const,
  },
  roundDuration: {
    type: 'int32' as const,
    default: 60,
    min: 10,
    max: 600,
  },
  startingScore: {
    type: 'int64' as const,
  },
  allowSpectators: {
    type: 'bool' as const,
    default: true,
  },
  tickRate: {
    type: 'int32' as const,
    default: 20,
    min: 1,
    max: 60,
  },
} as const;

/**
 * Create a GameConfig instance with partial values
 */
export function createGameConfig(partial: Partial<GameConfig>): GameConfig {
  return { ...defaultGameConfig, ...partial };
}


/**
 * MatchmakingConfig configuration interface
 */
export interface MatchmakingConfig {
  /** EnableSBMM configuration value */
  enableSBMM: boolean;
  /** MaxSkillGap configuration value */
  maxSkillGap: number;
  /** QueueTimeout configuration value */
  queueTimeout: number;
  /** MinPlayers configuration value */
  minPlayers: number;
}

/**
 * Default MatchmakingConfig configuration values
 */
export const defaultMatchmakingConfig: MatchmakingConfig = {
  enableSBMM: true,
  maxSkillGap: 500,
  queueTimeout: 120,
  minPlayers: 2,
};

/**
 * Validate MatchmakingConfig configuration
 * @returns Array of error messages (empty if valid)
 */
export function validateMatchmakingConfig(config: MatchmakingConfig): string[] {
  const errors: string[] = [];
  if (config.maxSkillGap < 100) { errors.push('MaxSkillGap must be >= 100'); }
  if (config.maxSkillGap > 2000) { errors.push('MaxSkillGap must be <= 2000'); }
  if (config.queueTimeout < 30) { errors.push('QueueTimeout must be >= 30'); }
  if (config.queueTimeout > 600) { errors.push('QueueTimeout must be <= 600'); }
  if (config.minPlayers < 2) { errors.push('MinPlayers must be >= 2'); }
  if (config.minPlayers > 10) { errors.push('MinPlayers must be <= 10'); }
  return errors;
}

/**
 * MatchmakingConfig configuration metadata for UI generation
 */
export const matchmakingConfigSchema = {
  enableSBMM: {
    type: 'bool' as const,
    default: true,
  },
  maxSkillGap: {
    type: 'int32' as const,
    default: 500,
    min: 100,
    max: 2000,
  },
  queueTimeout: {
    type: 'int32' as const,
    default: 120,
    min: 30,
    max: 600,
  },
  minPlayers: {
    type: 'int32' as const,
    default: 2,
    min: 2,
    max: 10,
  },
} as const;

/**
 * Create a MatchmakingConfig instance with partial values
 */
export function createMatchmakingConfig(partial: Partial<MatchmakingConfig>): MatchmakingConfig {
  return { ...defaultMatchmakingConfig, ...partial };
}


/**
 * Helper to deep merge configs
 */
export function mergeConfig<T extends object>(base: T, override: Partial<T>): T {
  const result = { ...base };
  for (const key in override) {
    if (override[key] !== undefined) {
      result[key] = override[key] as T[Extract<keyof T, string>];
    }
  }
  return result;
}
