// Code generated by schemagen. DO NOT EDIT.

import { Schema, SchemaRegistry, SyncState, defineSchema, FieldType, Decoder } from '@statediff/client';


// Player interface
export interface Player {
  ID: string;
  Name: string;
  Score: number;
  Hand: number[];
  Ready: boolean;
}

// GameState interface
export interface GameState {
  Round: number;
  Phase: string;
  Players: Player[];
  Scores: Record<string, number>;
  SecretSeed: number;
}


// Schema definitions

export const PlayerSchema: Schema = defineSchema(
  2,
  'Player',
  [
    {
      name: 'ID',
      type: FieldType.String,
    },
    {
      name: 'Name',
      type: FieldType.String,
    },
    {
      name: 'Score',
      type: FieldType.Int64,
    },
    {
      name: 'Hand',
      type: FieldType.Array,
      elemType: FieldType.Int32,
    },
    {
      name: 'Ready',
      type: FieldType.Bool,
    },
  ]
);

export const GameStateSchema: Schema = defineSchema(
  1,
  'GameState',
  [
    {
      name: 'Round',
      type: FieldType.Int32,
    },
    {
      name: 'Phase',
      type: FieldType.String,
    },
    {
      name: 'Players',
      type: FieldType.Array,
      elemType: FieldType.Struct,
      childSchema: PlayerSchema,
      keyField: 'ID',
    },
    {
      name: 'Scores',
      type: FieldType.Map,
      elemType: FieldType.Int64,
    },
    {
      name: 'SecretSeed',
      type: FieldType.Int64,
    },
  ]
);


// Create and configure registry
export function createRegistry(): SchemaRegistry {
  const registry = new SchemaRegistry();

  registry.register(PlayerSchema);
  registry.register(GameStateSchema);
  return registry;
}


// Player state container
export function createPlayerState(registry?: SchemaRegistry): SyncState<Player> {
  const reg = registry || createRegistry();
  return new SyncState<Player>(PlayerSchema, reg, {
    ID: '',
    Name: '',
    Score: 0,
    Hand: [],
    Ready: false,
  });
}

// GameState state container
export function createGameStateState(registry?: SchemaRegistry): SyncState<GameState> {
  const reg = registry || createRegistry();
  return new SyncState<GameState>(GameStateSchema, reg, {
    Round: 0,
    Phase: '',
    Players: [],
    Scores: {},
    SecretSeed: 0,
  });
}



// View types for projections

export type allView = 'all';

export type adminView = 'admin';

export type ownerView = 'owner';


export type ViewType = 'all' | 'admin' | 'owner';


// Re-export types for convenience
export { FieldType, Operation, Decoder, SchemaRegistry, SyncState } from '@statediff/client';
