coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 90%

ignore:
  - "example/**"
  - "cmd/clonegen/main.go"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
