package main

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// jsFieldType returns the FieldType enum name for a schema type
func jsFieldType(typ string) string {
	pt := ParseType(typ)
	if pt.IsArray {
		return "Array"
	}
	if pt.IsMap {
		return "Map"
	}
	switch pt.BaseType {
	case "string", "uuid":
		return "String"
	case "bool":
		return "Bool"
	case "int8", "int16", "int32":
		return "Int32"
	case "int", "int64":
		return "Int64"
	case "uint8", "uint16", "uint32":
		return "Uint32"
	case "uint", "uint64":
		return "Uint64"
	case "float32":
		return "Float32"
	case "float64":
		return "Float64"
	case "bytes", "[]byte":
		return "Bytes"
	default:
		return "Struct"
	}
}

// jsElemFieldType returns the FieldType for the element of an array or map
func jsElemFieldType(typ string) string {
	pt := ParseType(typ)
	if pt.IsArray || pt.IsMap {
		return jsFieldType(pt.ElemType)
	}
	return ""
}

// jsNeedsChildSchema returns true if an array/map element is a struct type
func jsNeedsChildSchema(typ string) bool {
	pt := ParseType(typ)
	if pt.IsArray || pt.IsMap {
		return !IsPrimitive(pt.ElemType)
	}
	return false
}

// jsChildSchemaName returns the variable name of the child schema
func jsChildSchemaName(typ string) string {
	pt := ParseType(typ)
	if pt.IsArray || pt.IsMap {
		if !IsPrimitive(pt.ElemType) {
			// e.g. "Player" → "playerSchema"
			return strings.ToLower(pt.ElemType[:1]) + pt.ElemType[1:] + "Schema"
		}
	}
	return "null"
}

// topologicalSort sorts types so that dependencies (child schemas) come before parents
func topologicalSort(types []*TypeDef) []*TypeDef {
	// Build dependency map
	deps := make(map[string][]string)
	byName := make(map[string]*TypeDef)
	for _, t := range types {
		byName[t.Name] = t
		for _, f := range t.Fields {
			pt := ParseType(f.Type)
			if pt.IsArray || pt.IsMap {
				if !IsPrimitive(pt.ElemType) {
					deps[t.Name] = append(deps[t.Name], pt.ElemType)
				}
			}
		}
	}

	visited := make(map[string]bool)
	var sorted []*TypeDef
	var visit func(name string)
	visit = func(name string) {
		if visited[name] {
			return
		}
		visited[name] = true
		for _, dep := range deps[name] {
			visit(dep)
		}
		if t, ok := byName[name]; ok {
			sorted = append(sorted, t)
		}
	}
	for _, t := range types {
		visit(t.Name)
	}
	return sorted
}

// GenerateJS generates JavaScript schema definitions for the statesync frontend decoder
func GenerateJS(schema *SchemaFile) ([]byte, error) {
	funcMap := template.FuncMap{
		"toCamelCase":       toCamelCase,
		"jsFieldType":       jsFieldType,
		"jsElemFieldType":   jsElemFieldType,
		"jsNeedsChildSchema": jsNeedsChildSchema,
		"jsChildSchemaName": jsChildSchemaName,
		"parseType":         ParseType,
		"isPrimitive":       IsPrimitive,
		"topologicalSort":   topologicalSort,
	}

	tmpl, err := template.New("js").Funcs(funcMap).Parse(jsTemplate)
	if err != nil {
		return nil, fmt.Errorf("template parse error: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, schema); err != nil {
		return nil, fmt.Errorf("template execute error: %w", err)
	}

	return buf.Bytes(), nil
}

const jsTemplate = `// Code generated by schemagen. DO NOT EDIT.
//
// Schema definitions for statesync binary decoding.
// Field indices match the Go schema. Field names use camelCase.

import { defineSchema, FieldType } from './decoder.js'

{{- $types := topologicalSort .Types}}
{{range $t := $types}}
export const {{toCamelCase $t.Name}}Schema = defineSchema({{$t.ID}}, '{{$t.Name}}', [
{{- range $i, $f := $t.Fields}}
{{- if $f.NoSync}}{{else}}
{{- $pt := parseType $f.Type}}
{{- if or $pt.IsArray $pt.IsMap}}
  { name: '{{toCamelCase $f.Name}}', type: FieldType.{{jsFieldType $f.Type}}, elemType: FieldType.{{jsElemFieldType $f.Type}}{{if jsNeedsChildSchema $f.Type}}, childSchema: {{jsChildSchemaName $f.Type}}{{end}} },  // {{$f.SyncIndex}}
{{- else if not (isPrimitive $f.Type)}}
  { name: '{{toCamelCase $f.Name}}', type: FieldType.Struct, childSchema: {{toCamelCase $f.Type}}Schema },  // {{$f.SyncIndex}}
{{- else}}
  { name: '{{toCamelCase $f.Name}}', type: FieldType.{{jsFieldType $f.Type}} },  // {{$f.SyncIndex}}
{{- end}}
{{- end}}
{{- end}}
])
{{end}}
// All schemas for registry
export const allSchemas = [
{{- range $t := $types}}
  {{toCamelCase $t.Name}}Schema,
{{- end}}
]
`
